#$schema: https://gitlab.com/gitlab-org/gitlab/-/raw/v14.4.0-ee/app/assets/javascripts/editor/schema/ci.json

include:
  - project: 'standard/cicd'
    ref: v1
    file:
      - '/standard/common.yml'

Build:
  script:
    - |
      echo "Building "
      set_env PROJECT_NAME llm-semantic-splitter-server
      set_env DOCKERFILE_PATH ./docker/Dockerfile

  extends: .build_manual

Release:
  extends:
    - .release-dev
  needs:
    - Build